//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scribd.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scribd.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.scribd.com/api.
        /// </summary>
        internal static string API_URL {
            get {
                return ResourceManager.GetString("API_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to log in..
        /// </summary>
        internal static string ERR_LOGIN_FAIL {
            get {
                return ResourceManager.GetString("ERR_LOGIN_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.ApiKey must be specified..
        /// </summary>
        internal static string ERR_NO_APIKEY {
            get {
                return ResourceManager.GetString("ERR_NO_APIKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.PublisherID must be specified..
        /// </summary>
        internal static string ERR_NO_PUBLISHERID {
            get {
                return ResourceManager.GetString("ERR_NO_PUBLISHERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.SecretKeyBytes must be specified..
        /// </summary>
        internal static string ERR_NO_SECRETKEY {
            get {
                return ResourceManager.GetString("ERR_NO_SECRETKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sign up for Scribd..
        /// </summary>
        internal static string ERR_SIGNUP_FAIL {
            get {
                return ResourceManager.GetString("ERR_SIGNUP_FAIL", resourceCulture);
            }
        }
    }
}
